export type Category =
  | "skincare"
  | "beauty"
  | "pet"
  | "music"
  | "electronics"
  | "home"
  | "desk"
  | "other";

export type CatalogueEntry = {
  title: string;
  merchant: string;
  seller: string;
  url: string;
  amountMinor: number;
  category: Category;
  /** Words a shopper would actually use for this. Drives matching, never shown. */
  keywords: string[];
};

/**
 * Real products on real Singapore storefronts. Generated by crawling each shop, then hand-kept.
 *
 * Every row came from the shop's own Shopify catalogue: the URL resolves, the title is the shop's
 * own wording, and the price is the DEFAULT single-unit variant. Each shop was separately
 * confirmed to serve real content to an AWS datacentre IP and to reach a card form at
 * `checkout.pci.shopifyinc.com` — the cross-origin PCI iframe the Closer's frame-searching filler
 * is already proven against.
 *
 * Every price sits inside S$5-30, because the StraitsX card refuses to mint outside that band and
 * a listing above it can never be bought.
 *
 * ## The variant trap
 *
 * Several shops, Cocomo especially, price at the VARIANT level as bundles: "(BUY 1) X",
 * "(BUY 2+1 FREE) X", "(BUY 3+2 FREE) X". Only the default "(BUY 1)" variant is in band; the
 * bundles run S$36-103. Every amountMinor here is that default.
 *
 * So an agent must never let a variant selector drift off the default. If it does, the merchant's
 * total exceeds the approved amount and the purchase is refused — correctly, by the total check —
 * but the useful behaviour is not to touch the selector at all.
 *
 * ## Categories
 *
 * `category` matters more than it looks. Matching is category-first, because plain word overlap
 * offered "Tangle-free" earphones for an "oil-free" moisturiser. Shared words are not shared
 * meaning. Categorise the PRODUCT, not the shop: a beauty shop's tote bag is "other".
 *
 * ## What is absent, deliberately
 *
 * Marketplaces. Shopee, Lazada and Amazon SG refuse automated browsers, and Shopee does so from a
 * residential IP as well as from AWS — it judges the automation, not the network, so nothing we
 * control reaches them. See docs/agentcore-browser.md.
 *
 * Prices drift. A purchase failing with "merchant total exceeds approved" means the shop moved its
 * price and this file is stale. That is the total check working, not a bug.
 */
const SELLERS: Record<string, string> = {
  "cocomo.sg": "COCOMO",
  "compasia.sg": "CompAsia",
  "polypet.com.sg": "Polypet",
  "prismplus.sg": "PRISM+",
  "secretlab.sg": "Secretlab",
  "sweelee.com.sg": "Swee Lee",
};

type Row = [
  merchant: string,
  amountMinor: number,
  title: string,
  url: string,
  category: Category,
  keywords: string[],
];

const rows: Row[] = [
  ["cocomo.sg", 1090, "[ORGANIST] Argan Oil Repair Shampoo 500ml", "https://www.cocomo.sg/products/organist-argan-oil-repair-shampoo-500ml", "beauty", ["shampoo", "hair", "argan", "oil", "damaged", "repair"]],
  ["cocomo.sg", 1250, "[AQUADUO] Showerhead Vitamin Filter (2-Pack)", "https://www.cocomo.sg/products/aquaduo-showerhead-vitamin-filter-showerhead-vitamin-filter-1-box-2-filters", "home", ["shower", "filter", "showerhead", "refill", "water", "vitamin"]],
  ["cocomo.sg", 1300, "[ISNTREE] Green Tea Fresh Cleanser 120ml", "https://www.cocomo.sg/products/isntree-green-tea-fresh-cleanser-120ml-cocomo", "skincare", ["cleanser", "face", "wash", "gel", "green", "tea"]],
  ["cocomo.sg", 1590, "[BLANC DUBU] Happy Breath Lemon Toothpaste 105g", "https://www.cocomo.sg/products/blanc-dubu-happy-breath-lemon-toothpaste-105g", "other", ["toothpaste", "teeth", "breath", "oral", "dental", "lemon"]],
  ["cocomo.sg", 1610, "[ISNTREE] Chestnut BHA 0.9% Clear Toner 200ml", "https://www.cocomo.sg/products/isntree-chestnut-bha-0-9-clear-toner-200ml", "skincare", ["toner", "bha", "exfoliating", "pores", "acne", "face"]],
  ["cocomo.sg", 1690, "[DONG-A] Aclean Gel 20g", "https://www.cocomo.sg/products/dong-a-aclean-gel-20g", "skincare", ["acne", "spot", "treatment", "gel", "pimple", "blemish"]],
  ["cocomo.sg", 1790, "[COSNORI] Flow Wave Lip Tint 3.7g", "https://www.cocomo.sg/products/cosnori-flow-wave-lip-tint-3-7g", "beauty", ["lip", "tint", "lipstick", "makeup", "gloss", "color"]],
  ["cocomo.sg", 1820, "[HEIMISH] All Clean Balm Mandarin 120ml", "https://www.cocomo.sg/products/heimish-all-clean-balm-mandarin-120ml", "skincare", ["cleansing", "balm", "makeup", "remover", "face", "sherbet"]],
  ["cocomo.sg", 1920, "[BEAUTY OF JOSEON] Matte Sun Stick SPF 50+ PA++++ 18g", "https://www.cocomo.sg/products/beauty-of-joseon-matte-sun-stick-spf-50-pa-18g", "skincare", ["sunscreen", "sun", "stick", "spf", "matte", "face"]],
  ["cocomo.sg", 1930, "[ANUA] Airy Sun Cream SPF 50+ PA++++ 50ml", "https://www.cocomo.sg/products/anua-airy-sun-cream-50ml", "skincare", ["sunscreen", "sun", "cream", "spf", "face", "lightweight"]],
  ["cocomo.sg", 1980, "[ABIB] Collagen Eye Patch Jericho Rose Jelly 90ml (60pcs | 30 pairs)", "https://www.cocomo.sg/products/abib-collagen-eye-patch-jericho-rose-jelly-90ml-60pcs-x-30-pairs", "skincare", ["eye", "patch", "collagen", "under", "eyes", "gel"]],
  ["cocomo.sg", 1990, "[ROUND LAB] Dokdo Cleanser 150ml", "https://www.cocomo.sg/products/round-lab-dokdo-cleanser-150ml-cocomo", "skincare", ["cleanser", "face", "wash", "foam", "gel", "skin"]],
  ["cocomo.sg", 1990, "[Mister Bower] Volume Gel Nail - Marrakesh", "https://www.cocomo.sg/products/mister-bower-volume-gel-nail-marrakesh", "beauty", ["nail", "stickers", "gel", "manicure", "press", "on"]],
  ["cocomo.sg", 2160, "[BEAUTY OF JOSEON] Ginseng Cleansing Oil 210ml", "https://www.cocomo.sg/products/beauty-of-joseon-ginseng-cleansing-oil-210ml", "skincare", ["cleansing", "oil", "face", "makeup", "remover", "ginseng"]],
  ["cocomo.sg", 2290, "(NUMBUZIN) No.3 Bifida Bakuchiol Exfoliating Toner Pad (190ml)", "https://www.cocomo.sg/products/numbuzin-no-3-bifida-bakuchiol-exfoliating-toner-pad-70-pads-190ml", "skincare", ["toner", "pad", "exfoliating", "face", "wipes", "bakuchiol"]],
  ["cocomo.sg", 2290, "[MAKEHEAL] Collagen Tint Lip Glow 4.5g", "https://www.cocomo.sg/products/makeheal-collagen-tint-lip-glow-4-5g", "beauty", ["lip", "tint", "balm", "makeup", "glow", "collagen"]],
  ["cocomo.sg", 2290, "[COLLINS] CHILL AQUA Fragrance Sachet 30g", "https://www.cocomo.sg/products/collins-chill-aqua-fragrance-sachet-30g", "home", ["sachet", "fragrance", "scent", "closet", "drawer", "freshener"]],
  ["cocomo.sg", 2320, "[MEDICUBE] Deep Vita C Capsule Serum 30ml", "https://www.cocomo.sg/products/medicube-deep-vita-c-capsule-serum-30ml", "skincare", ["serum", "vitamin", "c", "brightening", "face", "dark", "spots"]],
  ["cocomo.sg", 2405, "[ANUA] Rice 70 Glow Collagen Mask (1 Box = 38g x 4 Sheets)", "https://www.cocomo.sg/products/anua-rice-70-glow-collagen-mask-1-box-38g-x-4-sheets", "skincare", ["sheet", "mask", "face", "collagen", "rice", "glow"]],
  ["cocomo.sg", 2415, "[MEDICUBE] Collagen Night Wrapping Mask 75ml", "https://www.cocomo.sg/products/medicube-collagen-night-wrapping-mask-75ml", "skincare", ["sleeping", "mask", "night", "collagen", "face", "overnight"]],
  ["cocomo.sg", 2430, "[ARENCIA] Cloud Body & Scalp Scrub Mint & Lily 260g", "https://www.cocomo.sg/products/arencia-cloud-body-scalp-scrub-mint-lily-260g", "skincare", ["body", "scrub", "exfoliating", "scalp", "shower", "mint"]],
  ["cocomo.sg", 2490, "[MEDICUBE] Zero Pore Cream 2.0 50ml", "https://www.cocomo.sg/products/medicube-zero-pore-cream-2-0-50ml", "skincare", ["cream", "moisturizer", "pores", "face", "oily", "skin"]],
  ["cocomo.sg", 2490, "[COLLINS] Splash Diving Incense - Aqua Scent (1 Box = 70 Sticks)", "https://www.cocomo.sg/products/collins-splash-diving-incense-aqua-scent-1-box-70-sticks", "home", ["incense", "sticks", "scent", "fragrance", "room", "aroma"]],
  ["cocomo.sg", 2650, "[ROUND LAB] Birch Juice Moisturizing Serum 50ml", "https://www.cocomo.sg/products/round-lab-birch-juice-moisturizing-serum-50ml", "skincare", ["serum", "hydrating", "face", "moisturizing", "dry", "skin"]],
  ["cocomo.sg", 2700, "[ROUND LAB] Birch Juice Moisturizing Toner 300ml", "https://www.cocomo.sg/products/round-lab-birch-juice-moisturizing-toner-300ml", "skincare", ["toner", "hydrating", "face", "moisturizing", "skin"]],

  ["compasia.sg", 690, "Samsung Tangle-free Earphones IN-EAR IG935", "https://compasia.sg/products/samsung-tangle-free-earphones-in-ear-ig935?variant=44942288060665", "electronics", ["earphones", "in-ear", "wired", "headphones", "microphone", "earbuds"]],
  ["compasia.sg", 900, "IRIVER AT2000 Dynamic Driver in-Ear Headphones", "https://compasia.sg/products/iriver-at1000-dynamic-driver-in-ear-headphones?variant=46283060871417", "electronics", ["headphones", "earphones", "in-ear", "wired", "earbuds", "microphone"]],
  ["compasia.sg", 1290, "Baseus Screen Protector", "https://compasia.sg/products/it-show-event-baseus-screen-protector", "electronics", ["screen protector", "tempered glass", "phone", "screen", "glass", "protector"]],
  ["compasia.sg", 1790, "30W Fast Charging Set (Lightning)", "https://compasia.sg/products/copy-of-30w-fast-charging-set", "electronics", ["charger", "cable", "lightning", "adapter", "iphone", "fast charging"]],
  ["compasia.sg", 1790, "30W Fast Charging Type C", "https://compasia.sg/products/copy-of-30w-fast-charging-set-1", "electronics", ["charger", "cable", "type-c", "usb-c", "adapter", "fast charging"]],
  ["compasia.sg", 1790, "Type-C Fast Charging Set", "https://compasia.sg/products/30w-fast-charging-set-1", "electronics", ["charger", "cable", "type-c", "usb-c", "adapter", "30w"]],

  ["polypet.com.sg", 660, "Fancy Feast Grilled Chicken Feast in Gravy Multipack Canned Cat Food 85g x 6", "https://polypet.com.sg/products/fancy-feast-grilled-chicken-feast-in-gravy-multipack-canned-cat-food-85g-x-6", "pet", ["cat", "food", "wet", "canned", "chicken", "gravy"]],
  ["polypet.com.sg", 690, "Lulu Pure White Tofu Cat Litter 7L", "https://polypet.com.sg/products/lulu-pure-white-tofu-cat-litter-7l", "pet", ["cat", "litter", "tofu", "clumping", "flushable"]],
  ["polypet.com.sg", 690, "Nurture Pro Nourish Life Salmon Adult Dry Dog Food 300g", "https://polypet.com.sg/products/nurture-pro-nourish-life-salmon-adult-dry-dog-food-300g", "pet", ["dog", "food", "dry", "kibble", "salmon", "adult"]],
  ["polypet.com.sg", 750, "Cat's Best Anti-Tracking Cat Litter Mat", "https://polypet.com.sg/products/pp-exclusive-cats-best-anti-tracking-litter-mat", "pet", ["cat", "litter", "mat", "tracking", "trapper"]],
  ["polypet.com.sg", 750, "Ocean Free Royal Red Fish Food S 270g", "https://polypet.com.sg/products/ocean-free-royal-red-fish-food-s-270g", "pet", ["fish", "food", "pellets", "aquarium", "tropical"]],
  ["polypet.com.sg", 800, "Lambee Stainless Steel Heavy Bowl 20cm", "https://polypet.com.sg/products/lambee-stainless-steel-heavy-bowl-20cm", "pet", ["bowl", "stainless", "steel", "dog", "feeding", "dish"]],
  ["polypet.com.sg", 890, "Cat's Best Original Lock-In Wood Clumping Cat Litter 5L / 2.1kg (Oko Plus)", "https://polypet.com.sg/products/cats-best-original-cat-litter-clumping-lock-in-5l-2-1kg-oko-plus", "pet", ["cat", "litter", "wood", "clumping", "pellets"]],
  ["polypet.com.sg", 900, "Hello Pet Flea Comb (NHP118)", "https://polypet.com.sg/products/hello-pet-flea-comb-nhp118", "pet", ["flea", "comb", "grooming", "cat", "dog", "fur"]],
  ["polypet.com.sg", 940, "Witte Molen Top Fresh Chinchilla Bathing Sand 900g", "https://polypet.com.sg/products/witte-molen-top-fresh-chinchilla-bathing-sand-900g", "pet", ["chinchilla", "sand", "bath", "dust", "small", "animal"]],
  ["polypet.com.sg", 1080, "Zee.Cat Collar Suede", "https://polypet.com.sg/products/zee-cat-collar-suede", "pet", ["cat", "collar", "suede", "breakaway", "bell"]],
  ["polypet.com.sg", 1150, "TetraPro Colour Multi-Crisps 55g", "https://polypet.com.sg/products/tetrapro-colour-multi-crisps-55g", "pet", ["fish", "food", "flakes", "crisps", "aquarium", "tropical"]],
  ["polypet.com.sg", 1290, "Royal Canin Feline - Senior Ageing Sterilised 11+ Dry Cat Food 400g", "https://polypet.com.sg/products/royal-canin-feline-ageing-sterilised-12-400g", "pet", ["cat", "food", "dry", "kibble", "senior", "sterilised"]],
  ["polypet.com.sg", 1345, "Bioline Dog Deshedding Shampoo 250ml", "https://polypet.com.sg/products/bioline-dog-deshedding-shampoo-250ml", "pet", ["dog", "shampoo", "deshedding", "grooming", "wash", "coat"]],
  ["polypet.com.sg", 1350, "Spike Sheep Plush Dog Toy", "https://polypet.com.sg/products/spike-sheep-plush-dog-toy", "pet", ["dog", "toy", "plush", "squeaky", "soft", "sheep"]],
  ["polypet.com.sg", 1440, "Pets Workshop Stainless Steel Cat Litter Scoop 28.8cm x 10cm x 5cm", "https://polypet.com.sg/products/pets-workshop-stainless-steel-cat-litter-scoop-28-8cm-x-10cm-x-5cm", "pet", ["cat", "litter", "scoop", "stainless", "steel", "sifter"]],
  ["polypet.com.sg", 1560, "Red Dingo Dog Collar Hot Pink L", "https://polypet.com.sg/products/red-dingo-dog-collar-hot-pink-l", "pet", ["dog", "collar", "pink", "buckle", "large"]],
  ["polypet.com.sg", 1640, "Versele-Laga Exotic Fruit Mix for Parrots 600g", "https://polypet.com.sg/products/versele-laga-exotic-fruit-mix-for-parrots-600g", "pet", ["bird", "parrot", "food", "seed", "fruit", "mix"]],
  ["polypet.com.sg", 1700, "Catit Durable Bowl Small Pink 350ml", "https://polypet.com.sg/products/catit-durable-bowl-small-pink-350ml", "pet", ["cat", "bowl", "feeding", "dish", "water", "small"]],
  ["polypet.com.sg", 1750, "DoggyMan Home Beauty Professional Nail Clipper S", "https://polypet.com.sg/products/doggyman-home-beauty-professional-nail-clipper-s", "pet", ["nail", "clipper", "dog", "claw", "trimmer", "grooming"]],
  ["polypet.com.sg", 1830, "Kong Puppy Activity Ball (KP32)", "https://polypet.com.sg/products/kong-puppy-activity-ball-kp32", "pet", ["dog", "toy", "ball", "puppy", "chew", "treat"]],
  ["polypet.com.sg", 2090, "Zenith Chicken Adult Dry Dog Food 1.2kg", "https://polypet.com.sg/products/zenith-chicken-adult-dry-dog-food-1-2kg", "pet", ["dog", "food", "dry", "kibble", "chicken", "adult"]],
  ["polypet.com.sg", 2150, "Hoopet Pin Brush - Grey", "https://polypet.com.sg/products/hoopet-pin-brush-grey", "pet", ["brush", "pin", "grooming", "dog", "cat", "coat"]],
  ["polypet.com.sg", 2500, "Dogwood Kind & Gentle Hypoallergenic Dog Shampoo 290ml", "https://polypet.com.sg/products/dogwood-kind-gentle-hypoallergenic-dog-shampoo-290ml", "pet", ["dog", "shampoo", "hypoallergenic", "sensitive", "skin", "wash"]],
  ["polypet.com.sg", 2800, "USB Cat Laser Toy Ball White", "https://polypet.com.sg/products/usb-cat-laser-toy-ball-white", "pet", ["cat", "toy", "laser", "automatic", "interactive", "usb"]],
  ["polypet.com.sg", 2970, "Zee.Dog Leash Chop S", "https://polypet.com.sg/products/zee-dog-leash-chop-s", "pet", ["dog", "leash", "lead", "walking", "small"]],

  ["prismplus.sg", 695, "Aircon Miscellaneous Materials", "https://prismplus.sg/products/aircon-miscellaneous-materials", "home", ["insulation", "tape", "aircon", "black", "wrap", "installation"]],
  ["prismplus.sg", 890, "PRISM+ Nanobot Elite AI Accessories", "https://prismplus.sg/products/prism-nanobot-elite-ai-accessories", "home", ["side", "brush", "robot", "vacuum", "replacement", "nanobot"]],
  ["prismplus.sg", 1310, "Electrical Hardware", "https://prismplus.sg/products/electrical-hardware", "electronics", ["isolator", "switch", "electrical", "wiring", "phase", "socket"]],
  ["prismplus.sg", 1390, "PRISM+ Floor Cleaner", "https://prismplus.sg/products/prism-floor-cleaner", "home", ["floor", "cleaner", "mop", "solution", "cleaning", "liquid", "vacuum"]],
  ["prismplus.sg", 1590, "PRISM+ Nanobot Accessories", "https://prismplus.sg/products/prism-nanobot-accessories", "home", ["side", "brush", "robot", "vacuum", "spare", "nanobot"]],
  ["prismplus.sg", 1590, "PRISM+ Nanobot Pro Accessories", "https://prismplus.sg/products/prism-nanobot-pro-accessories", "home", ["side", "brush", "robot", "vacuum", "spare", "nanobot"]],
  ["prismplus.sg", 1900, "PRISM+ Dryer Aroma Capsule", "https://prismplus.sg/products/prism-dryer-aroma-capsule", "home", ["dryer", "aroma", "capsule", "fragrance", "laundry", "scent", "freshener"]],
  ["prismplus.sg", 1990, "PRISM+ Solaris and Solaris Pro Accessories", "https://prismplus.sg/products/prism-solaris-accesories", "home", ["remote", "control", "laundry", "rack", "drying", "solaris", "replacement"]],
  ["prismplus.sg", 2000, "PRISM+ Smart Lock RFID Cards & Stickers", "https://prismplus.sg/products/prism-door-lock-rfid-card", "home", ["rfid", "card", "smart", "lock", "door", "keycard", "access"]],
  ["prismplus.sg", 2990, "PRISM+ EvoHub", "https://prismplus.sg/products/prism-evohub", "home", ["vacuum", "stand", "cordless", "holder", "dock", "storage"]],
  ["prismplus.sg", 3000, "PRISM+ High Security Letterbox Lock", "https://prismplus.sg/products/prism-letterbox-lock", "home", ["letterbox", "lock", "mailbox", "security", "key", "door"]],
  ["prismplus.sg", 3000, "Washer and Dryer Accesories", "https://prismplus.sg/products/washer-and-dryer-accesories", "home", ["washer", "tap", "laundry", "washing", "machine", "hose", "fitting"]],

  ["secretlab.sg", 1400, "Secretlab Cable Fastening Straps", "https://secretlab.sg/products/cable-fastening-straps", "desk", ["cable", "straps", "tie", "management", "desk", "organizer"]],
  ["secretlab.sg", 1500, "Secretlab Assembly Toolkit", "https://secretlab.sg/products/secretlab-spare-parts-evo-toolkit", "other", ["toolkit", "allen", "key", "screwdriver", "screws", "assembly", "chair", "tools"]],
  ["secretlab.sg", 1500, "Secretlab Magnetic Side Covers (Left & Right)", "https://secretlab.sg/products/secretlab-spare-parts-evo-side-cover", "other", ["side", "cover", "magnetic", "chair", "replacement", "panel"]],
  ["secretlab.sg", 1900, "Secretlab Rubber Base Extender", "https://secretlab.sg/products/rubber-base-extender", "desk", ["footrest", "extender", "rubber", "base", "height", "riser"]],
  ["secretlab.sg", 1900, "Secretlab Armrest Top", "https://secretlab.sg/products/spare-parts", "other", ["armrest", "top", "pad", "arm", "chair", "replacement"]],
  ["secretlab.sg", 2400, "Secretlab Magnetic Bumpers (Set of 4)", "https://secretlab.sg/products/magnetic-bumpers", "desk", ["bumper", "magnetic", "desk", "leg", "protector", "guard"]],
  ["secretlab.sg", 2500, "Secretlab Magnetic Cable Anchors (Set of 3)", "https://secretlab.sg/products/magnetic-cable-anchors", "desk", ["cable", "anchor", "magnetic", "desk", "management", "clip"]],
  ["secretlab.sg", 3000, "Secretlab Leather Wipes", "https://secretlab.sg/products/leather-wipes", "home", ["wipes", "leather", "cleaner", "cleaning", "chair", "leatherette"]],
  ["secretlab.sg", 3000, "Secretlab SoftWeave® Fabric Wipes", "https://secretlab.sg/products/softweave-fabric-wipes", "home", ["wipes", "fabric", "cleaner", "cleaning", "chair", "upholstery"]],

  ["sweelee.com.sg", 500, "Sela SE-270 Professional Drumsticks 5A Maple", "https://www.sweelee.com.sg/products/sela-se-270-professional-drumsticks-5a-maple", "music", ["drumsticks", "drum", "sticks", "5a", "maple", "percussion"]],
  ["sweelee.com.sg", 500, "Sela SE-274 Professional Drumsticks 7A Maple", "https://www.sweelee.com.sg/products/sela-se-274-professional-drumsticks-7a-maple", "music", ["drumsticks", "drum", "sticks", "7a", "maple", "percussion"]],
  ["sweelee.com.sg", 600, "koda essential Multifunctional Guitar Spanner Wrench ONE 1 Piece", "https://www.sweelee.com.sg/products/koda-essential-multifunctional-guitar-spanner-wrench-one-1-piece", "music", ["wrench", "spanner", "guitar", "tool", "setup", "repair"]],
  ["sweelee.com.sg", 790, "Hosa CRA-103 Unbalanced Interconnect RCA to RCA Cable, 3ft", "https://www.sweelee.com.sg/products/hosa-cra-103-unbalanced-interconnect-rca-to-rca-cable-3ft", "electronics", ["rca cable", "audio cable", "interconnect", "stereo", "3ft"]],
  ["sweelee.com.sg", 850, "koda essential MIDI Cable, 3ft", "https://www.sweelee.com.sg/products/koda-essential-midi-cable-3ft", "music", ["midi cable", "midi", "din", "keyboard", "synth", "3ft"]],
  ["sweelee.com.sg", 1000, "Ernie Ball Silky Slinky Nickel Wound Electric Guitar Strings, 9.5-48", "https://www.sweelee.com.sg/products/ernie-ball-silky-slinky-nickel-wound-electric-guitar-strings-9-5-48", "music", ["guitar strings", "electric", "nickel wound", "string set", "slinky"]],
  ["sweelee.com.sg", 1000, "Morningstar DIN5 Midi Cable, 30 CM", "https://www.sweelee.com.sg/products/morningstar-din5-midi-cable-30-cm", "music", ["midi cable", "din5", "pedalboard", "short", "patch"]],
  ["sweelee.com.sg", 1090, "MEINL Percussion SH50 Mini Cajon Shaker, Natural", "https://www.sweelee.com.sg/products/meinl-percussion-sh50-mini-cajon-shaker-natural", "music", ["shaker", "percussion", "cajon", "hand percussion", "rhythm"]],
  ["sweelee.com.sg", 1200, "D'Addario 1CWH4-01AL Alchemy Picks Skull Collection 0.70mm Guitar Picks, 5-Pack", "https://www.sweelee.com.sg/products/d-addario-1cwh4-01al-alchemy-picks-skull-collection-0-70mm-guitar-picks-5-pack", "music", ["guitar picks", "plectrum", "pick", "0.70mm", "medium"]],
  ["sweelee.com.sg", 1200, "Behringer GMC150 XLR Female to XLR Male Microphone Cable - 5 Foot", "https://www.sweelee.com.sg/products/behringer-gmc150-xlr-female-to-xlr-male-microphone-cable-5-foot", "music", ["xlr cable", "microphone cable", "balanced", "mic lead", "5ft"]],
  ["sweelee.com.sg", 1500, "Ernie Ball Flex Capo, Black", "https://www.sweelee.com.sg/products/ernie-ball-flex-capo-black", "music", ["capo", "guitar", "acoustic", "electric", "clamp"]],
  ["sweelee.com.sg", 1500, "Chums Booby Bottle Opener, Black", "https://www.sweelee.com.sg/products/chums-booby-bottle-opener-black", "home", ["bottle opener", "opener", "keychain", "bar", "kitchen"]],
  ["sweelee.com.sg", 1600, "Baggu Baby Shopper Bag, Lambs", "https://www.sweelee.com.sg/products/baggu-baby-shopper-bag-lambs", "other", ["tote bag", "shopper", "reusable bag", "small", "fabric", "shopping"]],
  ["sweelee.com.sg", 1900, "Behringer BC110 Dynamic Vocal Microphone with 10-foot Cable", "https://www.sweelee.com.sg/products/behringer-bc110-dynamic-vocal-microphone-with-10-foot-cable", "music", ["microphone", "dynamic", "vocal", "mic", "cable", "singing"]],
  ["sweelee.com.sg", 1900, "Baggu Standard Shopper Bag, Gradient Stripe Multi", "https://www.sweelee.com.sg/products/baggu-standard-shopper-bag-gradient-stripe-multi", "other", ["tote bag", "shopper", "reusable bag", "grocery", "striped", "foldable"]],
  ["sweelee.com.sg", 2000, "Ernie Ball Fast Pitch Clip-On Tuner", "https://www.sweelee.com.sg/products/ernie-ball-fast-pitch-clip-on-tuner", "music", ["tuner", "clip on", "guitar", "chromatic", "headstock"]],
  ["sweelee.com.sg", 2100, "Fender FT-1 Pro Clip-On LCD Tuner", "https://www.sweelee.com.sg/products/fender-ft-1-pro-clip-on-lcd-tuner", "music", ["tuner", "clip on", "lcd", "guitar", "bass"]],
  ["sweelee.com.sg", 2200, "Ernie Ball Ball Precision Capo, Black", "https://www.sweelee.com.sg/products/ernie-ball-ball-precision-capo-black", "music", ["capo", "guitar", "precision", "acoustic", "fretboard"]],
  ["sweelee.com.sg", 2300, "D'Addario PW-CT-27 Eclipse Rechargeable Clip-on Tuner, Black", "https://www.sweelee.com.sg/products/d-addario-pw-ct-27-eclipse-rechargeable-clip-on-tuner-black", "music", ["tuner", "clip on", "rechargeable", "guitar", "chromatic"]],
  ["sweelee.com.sg", 2300, "Ernie Ball Guitar Neck Rest", "https://www.sweelee.com.sg/products/ernie-ball-guitar-neck-rest", "music", ["neck rest", "guitar", "luthier", "setup", "support", "cradle"]],
  ["sweelee.com.sg", 2400, "Bluescentric 3D Moon Graphic Turntable Slip Mat (AE)", "https://www.sweelee.com.sg/products/bluescentric-3d-moon-graphic-turntable-slip-mat-ae", "music", ["slipmat", "turntable", "record player", "vinyl", "mat", "platter"]],
  ["sweelee.com.sg", 2500, "Ernie Ball Braided 10ft Straight to Angle Instrument Cable, Pumpkin Pie", "https://www.sweelee.com.sg/products/ernie-ball-braided-10ft-straight-to-angle-instrument-cable-pumpkin-pie", "music", ["instrument cable", "guitar cable", "braided", "10ft", "right angle", "jack"]],
  ["sweelee.com.sg", 2500, "NINO Percussion NINO501 Caxixi", "https://www.sweelee.com.sg/products/nino-percussion-nino501-caxixi", "music", ["caxixi", "shaker", "percussion", "hand percussion", "woven", "rhythm"]],
  ["sweelee.com.sg", 2900, "Ernie Ball Classic Jacquard Bass/Guitar Strap, Dark Matter", "https://www.sweelee.com.sg/products/ernie-ball-classic-jacquard-bass-guitar-strap-dark-matter", "music", ["guitar strap", "bass", "strap", "woven", "jacquard"]],
  ["sweelee.com.sg", 2900, "Sela SETD4M1 Melody Series 4 Inch Tongue Drum w/Mallet in C Major, Black", "https://www.sweelee.com.sg/products/sela-setd4m1-melody-series-4-inch-tongue-drum-w-mallet-in-c-major-black", "music", ["tongue drum", "steel drum", "mallet", "percussion", "handpan", "4 inch"]],
];

export const CATALOGUE: CatalogueEntry[] = rows.map(
  ([merchant, amountMinor, title, url, category, keywords]) => ({
    merchant,
    seller: SELLERS[merchant] ?? merchant,
    title,
    url,
    amountMinor,
    category,
    keywords,
  }),
);

export const formatSgd = (amountMinor: number) => `S$${(amountMinor / 100).toFixed(2)}`;
