/**
 * The verified merchant list.
 *
 * "Verified" means the live storefront admits an automated browser and exposes the Shopify
 * surfaces Happy uses: rendered search, predictive product search and exact product JSON. The
 * first six shops behind `catalogue.ts` were additionally checked from an AWS datacentre IP, and
 * the checkout-focused shops in docs/merchant-shortlist.md were driven to a guest card form.
 * The initial discovery expansion was checked on 16 Aug 2026 with Playwright using AgentCore's
 * exact, automation-identifying user-agent; every entry had an available S$5-30 product at
 * verification. Later lower-priority entries state their narrower evidence in each block below.
 *
 * That difference is not bookkeeping. Measured 15 Aug: `nylon.coffee/search/suggest.json?q=coffee`
 * returned five products to a laptop and zero to the AgentCore browser in the same minute, after a
 * run of repeated probing. The shop is not down — it is answering an AWS IP differently, which is
 * the datacentre-egress wall docs/agentcore-browser.md predicts and cannot fix. Earlier runs did
 * get products from it, so this reads as throttling that hardens under load rather than a block.
 *
 * Two consequences. Prefer the AWS-verified six, which is why they are ordered first. And do not
 * rehearse the demo against these shops back to back — rapid cross-store cart probes eventually
 * trigger Shopify's shared 429/challenge path even when ordinary search and product browsing pass.
 *
 * Everything here is Shopify. That is not a coincidence: a Shopify storefront exposes a stable
 * `/search` and a per-product `.js` document, so a scout can read an exact price in cents rather
 * than parsing a rendered string. Marketplaces (Shopee, Lazada, Amazon.sg, FairPrice, COURTS) are
 * deliberately excluded — they bounce datacentre egress, or demand an account and a phone OTP.
 *
 * Scouts only ever visit hosts in this list. A listing from anywhere else cannot be shortlisted,
 * and would be denied at `rules.ts` anyway when it is not in the mandate's `merchants`.
 */
export interface VerifiedMerchant {
  id: string;
  /** Bare hostname. This is what goes in a mandate's `merchants` allowlist. */
  host: string;
  name: string;
  origin: string;
  /** What the storefront sells, used to steer a scout away from pointless searches. */
  sells: string;
  /** Flat delivery cost in cents, so a scout can keep the all-in total inside the card bounds. */
  shippingMinor: number;
  /**
   * Either newly discovery-verified or known to challenge under heavy probing. Established
   * AWS-verified merchants are visited first and these stores are probed at lower priority.
   */
  probeSparingly: boolean;
  note: string;
}

export const VERIFIED_MERCHANTS: VerifiedMerchant[] = [
  /*
   * The six below were verified the way that matters for this rail: each was confirmed to serve
   * real content to an AWS datacentre IP — which is exactly what an AgentCore browser egresses
   * from — and to reach a card form at checkout.pci.shopifyinc.com. They back `catalogue.ts`.
   *
   * They come first for that reason. Four legacy residential-only entries remain at the end;
   * reaching those locally says nothing about whether AWS egress gets through.
   */
  {
    id: "sweelee",
    host: "sweelee.com.sg",
    name: "Swee Lee",
    origin: "https://www.sweelee.com.sg",
    sells: "musical instruments, accessories, cables, drumsticks and picks",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Verified from an AWS IP. Small accessories sit inside the S$5-30 card band.",
  },
  {
    id: "cocomo",
    host: "cocomo.sg",
    name: "Cocomo",
    origin: "https://www.cocomo.sg",
    sells: "skincare, haircare and beauty",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Verified from an AWS IP. Prices bundles as variants — only the default is in band.",
  },
  {
    id: "polypet",
    host: "polypet.com.sg",
    name: "Polypet",
    origin: "https://polypet.com.sg",
    sells: "pet food, treats and small pet supplies",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Verified from an AWS IP.",
  },
  {
    id: "prismplus",
    host: "prismplus.sg",
    name: "PRISM+",
    origin: "https://prismplus.sg",
    sells: "consumer electronics, monitors and home appliance accessories",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Verified from an AWS IP. Many products carry 30+ variants; price the default only.",
  },
  {
    id: "secretlab",
    host: "secretlab.sg",
    name: "Secretlab",
    origin: "https://secretlab.sg",
    sells: "desk and chair accessories; the chairs themselves are far above the card band",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Verified from an AWS IP. Only the small accessories are buyable on this rail.",
  },
  {
    id: "compasia",
    host: "compasia.sg",
    name: "CompAsia",
    origin: "https://compasia.sg",
    sells: "refurbished phones and phone accessories",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Verified from an AWS IP. Accessories only; handsets exceed S$30.",
  },
  /*
   * Discovery expansion, verified 16 Aug 2026 with a real Playwright browser carrying the exact
   * AgentCore user-agent. Each shop rendered its search page without a delayed bot bounce, returned
   * products from `/search/suggest.json`, and returned a live integer price from `.js` product data.
   * They are intentionally lower-priority than the six AWS-egress-verified shops above.
   */
  {
    id: "spigen",
    host: "spigen.com.sg",
    name: "Spigen Singapore",
    origin: "https://spigen.com.sg",
    sells: "phone and tablet cases, charging cables, chargers, mounts and mobile accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 47 products in card range.",
  },
  {
    id: "bookiepen",
    host: "bookiepen.com",
    name: "BookiePen",
    origin: "https://www.bookiepen.com",
    sells: "pens, stamps, labels, stationery, school supplies and office accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 155 products in card range.",
  },
  {
    id: "soundteoh",
    host: "soundteoh.sg",
    name: "SOUNDTEOH",
    origin: "https://soundteoh.sg",
    sells: "cables, adapters, sockets, lights, fans and small household electronics",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 83 products in card range.",
  },
  {
    id: "casefactorie",
    host: "casefactorie.com",
    name: "Casefactorie",
    origin: "https://casefactorie.com",
    sells: "phone cases, tablet accessories, USB cables, chargers, stands and screen protectors",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 28 products in card range.",
  },
  {
    id: "equate",
    host: "equate.sg",
    name: "Equate Coffee",
    origin: "https://equate.sg",
    sells: "specialty filter coffee, espresso beans and roasted coffee",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; filter coffee is in card range.",
  },
  {
    id: "wakuwaku",
    host: "wakuwakupets.com.sg",
    name: "Waku Waku Pets",
    origin: "https://wakuwakupets.com.sg",
    sells: "dog and cat treats, pet food, toys, grooming products and pet accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 104 products in card range.",
  },
  {
    id: "battuta",
    host: "battutacoffee.com",
    name: "Battuta Coffee",
    origin: "https://battutacoffee.com",
    sells: "coffee beans, drip coffee, cold brew and coffee brewing accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 50 products in card range.",
  },
  {
    id: "gaiapets",
    host: "gaiapetshop.com",
    name: "Gaia Pets",
    origin: "https://gaiapetshop.com",
    sells: "pet food, treats, toys, grooming, litter and aquarium supplies",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 42 products in card range.",
  },
  {
    id: "artifek",
    host: "artifek.coffee",
    name: "artifek:coffee",
    origin: "https://artifek.coffee",
    sells: "specialty coffee beans and manual coffee brewing accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; limited card-range stock.",
  },
  {
    id: "outplay",
    host: "outplayworld.com",
    name: "OUTPLAY",
    origin: "https://www.outplayworld.com",
    sells: "dog toys, leashes, collars, bowls, bandanas and walking accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 22 products in card range.",
  },
  {
    id: "pppcoffee",
    host: "pppcoffee.com",
    name: "PPP Coffee",
    origin: "https://pppcoffee.com",
    sells: "specialty coffee beans, coffee capsules, filters, brewers and drinkware",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 136 products in card range.",
  },
  {
    id: "kohepets",
    host: "kohepets.com.sg",
    name: "Kohepets",
    origin: "https://www.kohepets.com.sg",
    sells: "dog and cat food, treats, toys, litter, grooming and pet accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 85 products in card range.",
  },
  {
    id: "cowpresso",
    host: "cowpressocoffee.sg",
    name: "Cowpresso Coffee Roasters",
    origin: "https://cowpressocoffee.sg",
    sells: "coffee beans, drip bags, coffee filters, milk pitchers and brewing gear",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; 65 products in card range.",
  },
  {
    id: "medicube",
    host: "themedicube.com.sg",
    name: "Medicube Singapore",
    origin: "https://themedicube.com.sg",
    sells: "facial cleansers, sheet masks, skincare creams, serums and beauty accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; skincare in card range.",
  },
  {
    id: "tionghoe",
    host: "tionghoe.com",
    name: "Tiong Hoe Specialty Coffee",
    origin: "https://tionghoe.com",
    sells: "coffee beans, coffee capsules, filters and coffee brewing accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; 15 products in card range.",
  },
  {
    id: "ginzacosme",
    host: "ginzacosme.com",
    name: "Ginza Cosme",
    origin: "https://ginzacosme.com",
    sells: "Japanese skincare, face masks, haircare and beauty products",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 15 products in card range.",
  },
  {
    id: "cityluxe",
    host: "cityluxe.sg",
    name: "Cityluxe",
    origin: "https://cityluxe.sg",
    sells: "notebooks, journals, planners, pens, pen cases and stationery accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; 79 products in card range.",
  },
  {
    id: "parables",
    host: "parablesgifts.com",
    name: "Parables Gifts",
    origin: "https://parablesgifts.com",
    sells: "gift items, enamel pins, plush toys, children's books and home gifts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; 16 products in card range.",
  },
  {
    id: "paperbunny",
    host: "thepaperbunny.com",
    name: "The Paper Bunny",
    origin: "https://thepaperbunny.com",
    sells: "bags, pouches, card holders, stationery, drinkware and small accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 60 products in card range.",
  },
  {
    id: "bettertoy",
    host: "thebettertoystore.com",
    name: "The Better Toy Store",
    origin: "https://thebettertoystore.com",
    sells: "children's toys, educational games, puzzles, baby toys and gifts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; 53 products in card range.",
  },
  {
    id: "hushcandle",
    host: "hushcandle.com",
    name: "Hush Candle",
    origin: "https://hushcandle.com",
    sells: "scented candles, room sprays, reed diffusers and fragrance gift sets",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 54 products in card range.",
  },
  {
    id: "littleshoptoys",
    host: "littleshop.toys",
    name: "LittleShop Toys",
    origin: "https://littleshop.toys",
    sells: "children's toys, educational toys, toy vehicles, games and gifts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 138 products in card range.",
  },
  {
    id: "kitchenary",
    host: "kitchenary.com.sg",
    name: "Kitchenary",
    origin: "https://kitchenary.com.sg",
    sells: "cookware, bakeware, cake pans, kitchen utensils and food storage",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 25 products in card range.",
  },
  {
    id: "playyard",
    host: "playyard.sg",
    name: "PlayYard",
    origin: "https://playyard.sg",
    sells: "children's clothing, pyjamas, toys, craft kits and kids' accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 180 products in card range.",
  },
  {
    id: "acharauntie",
    host: "acharauntiesg.com",
    name: "Achar Auntie SG",
    origin: "https://acharauntiesg.com",
    sells: "Singapore achar, pickles, chilli condiments and food gift bundles",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; five products in card range.",
  },
  {
    id: "littleoaktree",
    host: "thelittleoaktree.com",
    name: "the little oak tree",
    origin: "https://thelittleoaktree.com",
    sells: "baby toys, children's books, feeding accessories and family essentials",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 56 products in card range.",
  },
  {
    id: "pickme",
    host: "pickme.sg",
    name: "Pickme Grocer",
    origin: "https://pickme.sg",
    sells: "groceries, frozen food, meat, seafood, vegetables, snacks and pantry goods",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 130 products in card range.",
  },
  {
    id: "flipforjoy",
    host: "flipforjoy.com.sg",
    name: "Flip for Joy",
    origin: "https://www.flipforjoy.com.sg",
    sells: "Chinese children's books, bilingual books, picture books and educational books",
    shippingMinor: 0,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; free SG book delivery advertised.",
  },
  {
    id: "delibox",
    host: "delibox.sg",
    name: "DeliBox",
    origin: "https://delibox.sg",
    sells: "groceries, frozen food, meat, seafood, pantry goods and household supplies",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Guest checkout plus AgentCore-UA search verified; 59 products in card range.",
  },
  {
    id: "faithworks",
    host: "faithworks.com.sg",
    name: "Faithworks Bookstore",
    origin: "https://www.faithworks.com.sg",
    sells: "books, children's books, stationery, mugs, gifts and small home accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 122 products in card range.",
  },
  {
    id: "sgfr",
    host: "thesgfrstore.com",
    name: "The SGFR Store",
    origin: "https://www.thesgfrstore.com",
    sells: "snacks, candy, chocolate, popcorn, drinks and snack gift boxes",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 75 products in card range.",
  },
  {
    id: "tinyseeds",
    host: "tinyseedsbookshop.com",
    name: "Tiny Seeds Bookshop",
    origin: "https://tinyseedsbookshop.com",
    sells: "children's books, board books, activity books, journals and small gifts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 83 products in card range.",
  },
  {
    id: "beingkids",
    host: "beingkids.sg",
    name: "Being Kids",
    origin: "https://beingkids.sg",
    sells: "plush toys, children's toys, character gifts, keychains and small accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA browser search and product JSON verified; 130 products in card range.",
  },
  /*
   * Second discovery wave, checked 16 Aug 2026. The first group below returned a real Shopify
   * catalogue to the AgentCore-identifying user-agent before Shopify rate-limited the verification
   * IP across otherwise unrelated shops. Each catalogue contained available S$5-30 variants.
   */
  {
    id: "modernhome",
    host: "modernhome.sg",
    name: "Modern Home Singapore",
    origin: "https://modernhome.sg",
    sells: "kitchenware, cleaning supplies, storage, home tools and household accessories",
    shippingMinor: 0,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 14 products in card range.",
  },
  {
    id: "ecoland",
    host: "ecoland.com.sg",
    name: "Eco Land",
    origin: "https://ecoland.com.sg",
    sells: "plant pots, garden accessories, pebbles, planters and outdoor decor",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; six products in card range.",
  },
  {
    id: "babycentral",
    host: "baby-central.com.sg",
    name: "Baby Central Singapore",
    origin: "https://baby-central.com.sg",
    sells: "baby books, feeding essentials, bath products, toys and nursery accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 72 products in card range.",
  },
  {
    id: "rojakbaby",
    host: "therojakbaby.com",
    name: "The Rojak Baby",
    origin: "https://www.therojakbaby.com",
    sells: "baby and children's clothing, hair accessories, bags and small gifts",
    shippingMinor: 450,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 185 products in card range.",
  },
  {
    id: "notecosmetics",
    host: "note.sg",
    name: "NOTE Cosmetics Singapore",
    origin: "https://note.sg",
    sells: "makeup, lip products, eye pencils, concealers and beauty accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 89 products in card range.",
  },
  {
    id: "furryplanet",
    host: "furryplanet.com.sg",
    name: "Furry Planet",
    origin: "https://furryplanet.com.sg",
    sells: "pet wellness, treats, bowls, grooming products, dental care and pet toys",
    shippingMinor: 299,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 96 products in card range.",
  },
  {
    id: "expresspets",
    host: "expresspetsupplies.sg",
    name: "Express Pet Supplies",
    origin: "https://expresspetsupplies.sg",
    sells: "cat litter, pet food, treats, grooming products and pet accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 11 products in card range.",
  },
  {
    id: "gymsportz",
    host: "gymsportz.sg",
    name: "Gymsportz",
    origin: "https://gymsportz.sg",
    sells: "resistance bands, exercise mats, gym accessories and fitness equipment",
    shippingMinor: 1090,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 47 products in card range; S$10.90 delivery below S$200.",
  },
  {
    id: "nanapaper",
    host: "nanapaperstudio.com",
    name: "Nana Paper Studio",
    origin: "https://nanapaperstudio.com",
    sells: "paper, envelopes, cards, craft tools, stickers and office supplies",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 80 products in card range.",
  },
  {
    id: "cyclistmess",
    host: "thecyclistmess.com",
    name: "The Cyclist Mess",
    origin: "https://thecyclistmess.com",
    sells: "cycling socks, bottles, small bicycle accessories and cycling apparel",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 41 products in card range.",
  },
  {
    id: "aslansports",
    host: "aslansports.com",
    name: "Aslan Sports",
    origin: "https://aslansports.com",
    sells: "martial arts apparel, protectors, wraps and combat-sports accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "AgentCore-UA product catalogue verified; 10 products in card range.",
  },
  /*
   * Shopify's shared rate-limit engaged before the remaining shops could be re-probed from the
   * same IP. These entries have current search-indexed Shopify collections or product pages with
   * live SGD stock and Singapore fulfilment, but remain low-priority until an AWS-egress pass.
   */
  {
    id: "mamax",
    host: "mamaxsg.com",
    name: "MamaX",
    origin: "https://mamaxsg.com",
    sells: "children's toys, Montessori toys, remote-control toys and pretend-play sets",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with available S$5-30 products; Singapore ready stock.",
  },
  {
    id: "theplayhouse",
    host: "theplayhouse.sg",
    name: "The Playhouse",
    origin: "https://theplayhouse.sg",
    sells: "baby products, children's books, puzzles, educational toys and play mats",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with available S$5-30 products; local delivery advertised.",
  },
  {
    id: "rumahhome",
    host: "rumahhome.com",
    name: "RumahHome",
    origin: "https://rumahhome.com",
    sells: "home tools, storage, kitchenware, laptop stands, bags and small household goods",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with broad available S$5-30 stock in Singapore.",
  },
  {
    id: "yumsay",
    host: "yumsayfoods.com",
    name: "Yumsay Foods",
    origin: "https://www.yumsayfoods.com",
    sells: "frozen Singapore meals, noodles, laksa, pasta and ready-to-heat food bundles",
    shippingMinor: 1000,
    probeSparingly: true,
    note: "Live Shopify collection indexed with available S$6.90-29.90 products; frozen delivery.",
  },
  {
    id: "warisanrecipe",
    host: "warisanrecipe.sg",
    name: "Warisan Recipe",
    origin: "https://warisanrecipe.sg",
    sells: "bahulu cakes, local baked snacks and food gifts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with available S$8-30 products.",
  },
  {
    id: "nastycookie",
    host: "nastycookie.com",
    name: "Nasty Cookie",
    origin: "https://www.nastycookie.com",
    sells: "fresh cookies, crispy cookie packs, dessert spreads and cookie gift boxes",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with available S$6-30 products and Singapore pickup.",
  },
  {
    id: "redlipsfoods",
    host: "redlipsfoods.com",
    name: "Red Lips Foods",
    origin: "https://www.redlipsfoods.com",
    sells: "kueh pie tee shells, gourmet shells, chilli sauce and local food bundles",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with available S$5.50-29 products in Singapore.",
  },
  {
    id: "kaicycle",
    host: "kaicycle.sg",
    name: "KAICYCLE",
    origin: "https://www.kaicycle.sg",
    sells: "bicycle kickstands, lights, mounts, sleeves and small cycling accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Indexed product pages expose live Shopify variant JSON and integer prices in card range.",
  },
  {
    id: "squarebox",
    host: "squareboxcycles.com",
    name: "Squarebox Cycles",
    origin: "https://squareboxcycles.com",
    sells: "bicycle tools, repair accessories, lights, grips and small bike parts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collections indexed with available S$5-30 bicycle accessories.",
  },
  {
    id: "kose",
    host: "kose.com.sg",
    name: "KOSÉ Singapore",
    origin: "https://kose.com.sg",
    sells: "skincare, cleansers, haircare, makeup and beauty accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify catalogue indexed with hundreds of products and broad S$5-30 stock.",
  },
  {
    id: "gryphon",
    host: "gryphontea.com",
    name: "Gryphon Tea Company",
    origin: "https://gryphontea.com",
    sells: "tea sachets, loose-leaf tea, cold brew tea and tea gifts",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Singapore Shopify catalogue indexed with in-range tea products.",
  },
  {
    id: "amazingraze",
    host: "amazingraze.com.sg",
    name: "Amazin' Graze Singapore",
    origin: "https://www.amazingraze.com.sg",
    sells: "granola, trail mix, nut mix, oatmeal and healthy snacks",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Singapore collection indexed with extensive available S$5-30 stock.",
  },
  {
    id: "motherswork",
    host: "motherswork.com.sg",
    name: "Motherswork",
    origin: "https://motherswork.com.sg",
    sells: "diapers, baby feeding, bath, hygiene, toys, books and maternity essentials",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify catalogue indexed with more than 1,300 in-stock baby and family products.",
  },
  {
    id: "balancedliving",
    host: "balancedlivingasia.com",
    name: "Balanced Living",
    origin: "https://www.balancedlivingasia.com",
    sells: "natural cleaning, wellness books, essential oils and healthy home accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Singapore Shopify collections indexed with available S$5-30 household products.",
  },
  {
    id: "atdtogo",
    host: "atdtogo.sg",
    name: "ATD To Go",
    origin: "https://atdtogo.sg",
    sells: "coffee, bakery items, desserts, sandwiches and prepared food",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify product page indexed with in-range Singapore food and coffee.",
  },
  {
    id: "essara",
    host: "essaraofficial.com",
    name: "ESSARA",
    origin: "https://essaraofficial.com",
    sells: "women's shawls, scarves, tops and modest-fashion accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Singapore Shopify collection indexed with available S$17-30 fashion items.",
  },
  {
    id: "averyday",
    host: "shopaveryday.com",
    name: "AveryDay",
    origin: "https://shopaveryday.com",
    sells: "women's tops, dresses, bottoms, outerwear and fashion accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Shopify collection indexed with hundreds of products and available S$20-30 tops.",
  },
  {
    id: "brints",
    host: "brintsco.com",
    name: "Brints Collectibles",
    origin: "https://brintsco.com",
    sells: "trading cards, playing cards, card sleeves, binders and collectible accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Singapore Shopify collections indexed with extensive available S$5-30 stock.",
  },
  {
    id: "shimanosg",
    host: "shimanosingapore.myshopify.com",
    name: "Shimano Singapore Online Store",
    origin: "https://shimanosingapore.myshopify.com",
    sells: "cycling socks, gloves, bottle cages, helmet parts and bicycle accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Official Shopify collection indexed with available S$5-30 cycling parts and apparel.",
  },
  {
    id: "haba",
    host: "haba.com.sg",
    name: "HABA Singapore",
    origin: "https://haba.com.sg",
    sells: "skincare, face sheets, cosmetic puffs and beauty accessories",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Live Singapore Shopify collections indexed with available S$5-30 beauty products.",
  },
  {
    id: "artifactt",
    host: "artifactt.com",
    name: "Artifactt",
    origin: "https://www.artifactt.com",
    sells: "tableware, spoons, cutlery, drinkware and small homeware",
    shippingMinor: 500,
    probeSparingly: true,
    note: "Indexed Shopify product pages expose in-stock S$19 tableware and Singapore fulfilment.",
  },
  {
    id: "wardah",
    host: "wardahbooks.com",
    name: "Wardah Books",
    origin: "https://wardahbooks.com",
    sells: "books, mostly literature, history and Islamic studies",
    shippingMinor: 0,
    probeSparingly: false,
    note: "Local pickup at 58 Bussorah Street makes the total the shelf price. Card fields live in checkout.pci.shopifyinc.com.",
  },
  {
    id: "nylon",
    host: "nylon.coffee",
    name: "Nylon Coffee Roasters",
    origin: "https://nylon.coffee",
    sells: "specialty coffee beans, filters and brewing accessories",
    shippingMinor: 380,
    probeSparingly: false,
    note: "One gateway on the checkout and no wallet tile to wander into.",
  },
  {
    id: "yongseng",
    host: "yongsengcoffee.com",
    name: "Yong Seng Coffee",
    origin: "https://yongsengcoffee.com",
    sells: "traditional kopi powder, tea and local drink supplies",
    shippingMinor: 470,
    probeSparingly: false,
    note: "A cheap delivery option is preselected.",
  },
  {
    id: "drom",
    host: "thelittledromstore.com",
    name: "the little dröm store",
    origin: "https://thelittledromstore.com",
    sells: "stationery, desk goods and small design objects",
    shippingMinor: 190,
    probeSparingly: true,
    note: "Flat S$1.90 shipping. Heavy probing has earned a sticky Cloudflare challenge before.",
  },
];

export function merchantById(id: string): VerifiedMerchant | undefined {
  return VERIFIED_MERCHANTS.find((merchant) => merchant.id === id);
}

export function isVerifiedHost(host: string): boolean {
  const bare = host.replace(/^www\./, "").toLowerCase();
  return VERIFIED_MERCHANTS.some((merchant) => merchant.host === bare);
}

/**
 * Scouts are split across the list rather than all racing the same storefront, so two slots on the
 * same item cover four merchants between them and the tiles show different pages.
 */
export function merchantsForSlot(slot: number, slots: number): VerifiedMerchant[] {
  const ordered = [...VERIFIED_MERCHANTS].sort((a, b) =>
    a.probeSparingly === b.probeSparingly ? 0 : a.probeSparingly ? 1 : -1,
  );
  return ordered.filter((_, index) => index % slots === slot % slots);
}
